// Code generated by protoc-gen-go. DO NOT EDIT.
// source: goods.proto

/*
Package go_micro_srv_goods is a generated protocol buffer package.

It is generated from these files:
	goods.proto

It has these top-level messages:
	Good
	Request
	Response
	DeleteRequest
	DeleteResponse
	InfoRequest
	InfoResponse
*/
package go_micro_srv_goods

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Good struct {
	GoodsID   int32  `protobuf:"varint,1,opt,name=goods_id" json:"goods_id"`
	GoodsName string `protobuf:"bytes,2,opt,name=goods_name" json:"goods_name"`
	CreatedAt int32  `protobuf:"varint,3,opt,name=created_at" json:"created_at"`
	UpdatedAt int32  `protobuf:"varint,4,opt,name=updated_at" json:"updated_at"`
}

func (m *Good) Reset()                    { *m = Good{} }
func (m *Good) String() string            { return proto.CompactTextString(m) }
func (*Good) ProtoMessage()               {}
func (*Good) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Good) GetGoodsID() int32 {
	if m != nil {
		return m.GoodsID
	}
	return 0
}

func (m *Good) GetGoodsName() string {
	if m != nil {
		return m.GoodsName
	}
	return ""
}

func (m *Good) GetCreatedAt() int32 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Good) GetUpdatedAt() int32 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type Request struct {
	Name    string `protobuf:"bytes,1,opt,name=name" json:"name"`
	BarCode string `protobuf:"bytes,2,opt,name=bar_code" json:"bar_code"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Request) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Request) GetBarCode() string {
	if m != nil {
		return m.BarCode
	}
	return ""
}

type Response struct {
	Status int32   `protobuf:"varint,1,opt,name=status" json:"status"`
	Msg    string  `protobuf:"bytes,2,opt,name=msg" json:"msg"`
	Data   []*Good `protobuf:"bytes,3,rep,name=data" json:"data"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Response) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *Response) GetData() []*Good {
	if m != nil {
		return m.Data
	}
	return nil
}

type DeleteRequest struct {
	GoodsId string `protobuf:"bytes,1,opt,name=goods_id,json=goods_id" json:"goods_id"`
}

func (m *DeleteRequest) Reset()                    { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()               {}
func (*DeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *DeleteRequest) GetGoodsId() string {
	if m != nil {
		return m.GoodsId
	}
	return ""
}

type DeleteResponse struct {
	Status int32  `protobuf:"varint,1,opt,name=status" json:"status"`
	Msg    string `protobuf:"bytes,2,opt,name=msg" json:"msg"`
}

func (m *DeleteResponse) Reset()                    { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()               {}
func (*DeleteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *DeleteResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *DeleteResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type InfoRequest struct {
	BrandId      int32  `protobuf:"varint,1,opt,name=brand_id" json:"brand_id"`
	BusinessCode string `protobuf:"bytes,2,opt,name=business_code,json=business_code" json:"business_code"`
}

func (m *InfoRequest) Reset()                    { *m = InfoRequest{} }
func (m *InfoRequest) String() string            { return proto.CompactTextString(m) }
func (*InfoRequest) ProtoMessage()               {}
func (*InfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *InfoRequest) GetBrandId() int32 {
	if m != nil {
		return m.BrandId
	}
	return 0
}

func (m *InfoRequest) GetBusinessCode() string {
	if m != nil {
		return m.BusinessCode
	}
	return ""
}

type InfoResponse struct {
	Status int32  `protobuf:"varint,1,opt,name=status" json:"status"`
	Msg    string `protobuf:"bytes,2,opt,name=msg" json:"msg"`
	Data   *Good  `protobuf:"bytes,3,opt,name=data" json:"data"`
}

func (m *InfoResponse) Reset()                    { *m = InfoResponse{} }
func (m *InfoResponse) String() string            { return proto.CompactTextString(m) }
func (*InfoResponse) ProtoMessage()               {}
func (*InfoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *InfoResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *InfoResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *InfoResponse) GetData() *Good {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Good)(nil), "go.micro.srv.goods.Good")
	proto.RegisterType((*Request)(nil), "go.micro.srv.goods.Request")
	proto.RegisterType((*Response)(nil), "go.micro.srv.goods.Response")
	proto.RegisterType((*DeleteRequest)(nil), "go.micro.srv.goods.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "go.micro.srv.goods.DeleteResponse")
	proto.RegisterType((*InfoRequest)(nil), "go.micro.srv.goods.InfoRequest")
	proto.RegisterType((*InfoResponse)(nil), "go.micro.srv.goods.InfoResponse")
}

func init() { proto.RegisterFile("goods.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 384 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0x41, 0x6b, 0xe2, 0x40,
	0x14, 0xde, 0x98, 0x68, 0xf4, 0xa9, 0xcb, 0xf2, 0x0e, 0x4b, 0xd6, 0x15, 0x36, 0x3b, 0x7b, 0x91,
	0x65, 0xc9, 0xc1, 0x3d, 0x14, 0x7a, 0x6b, 0xb5, 0x94, 0xd0, 0x22, 0x34, 0xd0, 0xb3, 0x4c, 0x9c,
	0x51, 0x02, 0x9a, 0xb1, 0x99, 0xb1, 0x87, 0xfe, 0xb8, 0xfe, 0xb6, 0x32, 0x93, 0x8c, 0xb6, 0x34,
	0x6d, 0x29, 0xed, 0xc9, 0x79, 0xef, 0xfb, 0xde, 0xf7, 0xbe, 0xf9, 0xc6, 0x40, 0x77, 0x25, 0x04,
	0x93, 0xd1, 0xb6, 0x10, 0x4a, 0x20, 0xae, 0x44, 0xb4, 0xc9, 0x16, 0x85, 0x88, 0x64, 0x71, 0x1b,
	0x19, 0x84, 0xdc, 0x81, 0x77, 0x2e, 0x04, 0xc3, 0x00, 0x7c, 0xfd, 0x2b, 0xe3, 0x69, 0xe0, 0x84,
	0xce, 0xa8, 0x99, 0xd8, 0x12, 0x87, 0xd0, 0x31, 0xc7, 0x19, 0xdd, 0xf0, 0xa0, 0x11, 0x3a, 0xa3,
	0x4e, 0x72, 0x68, 0x68, 0x74, 0x52, 0x70, 0xaa, 0x38, 0x3b, 0x51, 0x81, 0x6b, 0x26, 0x0f, 0x0d,
	0x8d, 0x5e, 0x6f, 0x59, 0x85, 0x7a, 0x25, 0xba, 0x6f, 0x90, 0x23, 0xf0, 0x13, 0x7e, 0xb3, 0xe3,
	0x52, 0x21, 0x82, 0x97, 0x6b, 0x7d, 0xc7, 0xe8, 0x9b, 0xb3, 0xb6, 0x94, 0xd2, 0x62, 0x22, 0x98,
	0x5d, 0x6b, 0x4b, 0x92, 0x42, 0x3b, 0xe1, 0x72, 0x2b, 0x72, 0xc9, 0xf1, 0x3b, 0xb4, 0xa4, 0xa2,
	0x6a, 0x27, 0x2b, 0xdf, 0x55, 0x85, 0xdf, 0xc0, 0xdd, 0xc8, 0x55, 0x35, 0xa9, 0x8f, 0xf8, 0x0f,
	0x3c, 0x46, 0x15, 0x0d, 0xdc, 0xd0, 0x1d, 0x75, 0xc7, 0x41, 0xf4, 0x3c, 0x8d, 0x48, 0xdf, 0x2b,
	0x31, 0x2c, 0xf2, 0x17, 0xfa, 0x53, 0xbe, 0xe6, 0x8a, 0x5b, 0x8b, 0x3f, 0xa0, 0x6d, 0x48, 0xf3,
	0x8c, 0x55, 0x36, 0x7d, 0x53, 0xc7, 0x8c, 0x1c, 0xc3, 0x57, 0xcb, 0x7d, 0xaf, 0x2b, 0x72, 0x09,
	0xdd, 0x38, 0x5f, 0x0a, 0xbb, 0x25, 0x00, 0xff, 0xb4, 0xa0, 0x39, 0x8b, 0x99, 0x7d, 0x87, 0xaa,
	0xc4, 0x3f, 0xd0, 0x4f, 0x77, 0x32, 0xcb, 0xb9, 0x94, 0xf3, 0xc5, 0x21, 0x94, 0x9e, 0x6d, 0x9a,
	0x64, 0x96, 0xd0, 0x2b, 0xd5, 0x3e, 0x90, 0x8e, 0xf3, 0x76, 0x3a, 0xe3, 0xfb, 0x06, 0x34, 0xcd,
	0x9f, 0x00, 0xcf, 0xa0, 0x35, 0xe5, 0x8a, 0x66, 0x6b, 0xfc, 0x59, 0x37, 0x53, 0xdd, 0x6b, 0x30,
	0xac, 0x07, 0x4b, 0x9b, 0xe4, 0x0b, 0x5e, 0x69, 0x19, 0x1d, 0x21, 0xfe, 0xae, 0x63, 0x3e, 0x79,
	0x8a, 0x01, 0x79, 0x8d, 0xb2, 0x97, 0xbc, 0x00, 0x4f, 0x67, 0x81, 0xbf, 0xea, 0xd8, 0x8f, 0x32,
	0x1f, 0x84, 0x2f, 0x13, 0xf6, 0x62, 0x33, 0xf0, 0xcb, 0x05, 0xe3, 0x4f, 0xd1, 0x4b, 0x5b, 0xe6,
	0x93, 0xfc, 0xff, 0x10, 0x00, 0x00, 0xff, 0xff, 0xda, 0x52, 0x65, 0xc1, 0xa1, 0x03, 0x00, 0x00,
}
